"""Derive wheel-builder pins from the installed full lock, without runtime extras."""

import argparse
import tomllib
from pathlib import Path

from packaging.requirements import Requirement
from runtime_lock import dependency_closure, locked_pins


def render(root: Path) -> str:
    project = tomllib.loads((root / "backend/pyproject.toml").read_text(encoding="utf-8"))
    roots = [Requirement("build"), *map(Requirement, project["build-system"]["requires"])]
    pins = locked_pins(root, dependency_closure(roots))
    return (
        "# Generated by python scripts/build_lock.py from the installed full lock.\n"
        + "\n".join(pins)
        + "\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    target = root / "requirements-build-lock.txt"
    value = render(root)
    if args.check:
        if target.read_text(encoding="utf-8") != value:
            raise SystemExit("Build dependency lock drift")
    else:
        target.write_text(value, encoding="utf-8")
