"""Derive production-only pins from the installed locked dependency graph."""

import argparse
import tomllib
from importlib.metadata import distribution
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


def supported_platforms() -> list[dict[str, str]]:
    platforms = []
    for platform, system, os_name in (
        ("linux", "Linux", "posix"),
        ("win32", "Windows", "nt"),
        ("darwin", "Darwin", "posix"),
    ):
        for version in ("3.11", "3.12", "3.13"):
            platforms.append(
                default_environment()
                | {
                    "sys_platform": platform,
                    "platform_system": system,
                    "os_name": os_name,
                    "python_version": version,
                    "python_full_version": version + ".0",
                }
            )
    return platforms


def active_dependency(
    requirement: Requirement, platforms: list[dict[str, str]], extras: tuple[str, ...]
) -> bool:
    if requirement.marker is None:
        return True
    return any(
        requirement.marker.evaluate(environment | {"extra": extra})
        for environment in platforms
        for extra in ("", *extras)
    )


def dependency_closure(queue: list[Requirement]) -> set[str]:
    visited: set[tuple[str, tuple[str, ...]]] = set()
    required: set[str] = set()
    platforms = supported_platforms()
    while queue:
        requirement = queue.pop()
        name = canonicalize_name(requirement.name)
        extras = tuple(sorted(requirement.extras))
        identity = (name, extras)
        if identity in visited:
            continue
        visited.add(identity)
        required.add(name)
        for value in distribution(name).requires or []:
            dependency = Requirement(value)
            if active_dependency(dependency, platforms, extras):
                queue.append(dependency)
    return required


def locked_pins(root: Path, required: set[str]) -> list[str]:
    pins = []
    for line in (root / "requirements-lock.txt").read_text(encoding="utf-8").splitlines():
        if (
            line
            and not line.startswith("#")
            and canonicalize_name(Requirement(line).name) in required
        ):
            pins.append(line)
    if {canonicalize_name(Requirement(line).name) for line in pins} != required:
        raise ValueError("Production dependency is missing from the full lock")
    return pins


def render(root: Path) -> str:
    project = tomllib.loads((root / "backend/pyproject.toml").read_text(encoding="utf-8"))
    required = dependency_closure(
        [Requirement(value) for value in project["project"]["dependencies"]]
    )
    pins = locked_pins(root, required)
    return (
        "# Generated by python scripts/runtime_lock.py from the installed full lock.\n"
        + "\n".join(pins)
        + "\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    target = root / "requirements-runtime-lock.txt"
    value = render(root)
    if args.check:
        if target.read_text(encoding="utf-8") != value:
            raise SystemExit("Production dependency lock drift")
    else:
        target.write_text(value, encoding="utf-8")
